1server:
  port: 8083

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      auto-commit: false
    url: jdbc:postgresql://database-1.cfsxy9eyo0nn.us-east-2.rds.amazonaws.com:5432/speech_dev
    username: postgres
    password: admin123
    tomcat:
      initial-size: 5
      max-wait: 10000
      max-active: 10
      max-idle: 5
      min-idle: 5
      default-auto-commit: true